name: CI
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/cache-apt-packages
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          purs-tidy: "latest"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}-2
          path: |
            .spago
            output

      - name: Install dependencies
        run: spago install

      - name: Install plugin dependencies
        run: spago -x spago-plugin.dhall install

      - name: Install test dependencies
        run: spago -x spago-test.dhall install

      - name: Build plugin
        run: spago build -x spago-plugin.dhall --no-install --purs-args '--censor-lib --strict --censor-codes='UserDefinedWarning''

      - name: Generate test from .proto
        run: mkdir -p ./test/generated
        run: protoc --purescript_out=./test/generated test/*.proto

      - name: Build test
        run: spago build -x spago-test.dhall --no-install --purs-args '--censor-lib --strict --censor-codes='UserDefinedWarning''

      - name: Run tests
        run: spago -x spago-test.dhall test --no-install

      # We're not running the conformance test because the conformance
      # test runner is a pretty heavy build.